name: PR Comments to CSV

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  export-pr-comments:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install PyGithub pandas
        
    - name: Export PR comments to CSV
      id: export
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/export_pr_comments.py
        echo "export_completed=true" >> $GITHUB_OUTPUT
        
    - name: Upload CSV artifact
      if: steps.export.outputs.export_completed == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: pr-comments-export
        path: pr_comments_export.csv
        retention-days: 30
        
    - name: Create comment with CSV data
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          let comment = '';
          let csvContent = '';
          let rowCount = 0;
          
          try {
            // CSVファイルの存在チェック
            if (fs.existsSync('pr_comments_export.csv')) {
              csvContent = fs.readFileSync('pr_comments_export.csv', 'utf8');
              rowCount = csvContent.split('\n').length - 1; // ヘッダーを除く
              
              comment = `## PR Comments Export ✅
              
              CSVファイルが正常に生成されました。アーティファクトとしてダウンロードできます。
              
              **ファイル名:** pr_comments_export.csv
              **生成日時:** ${new Date().toISOString()}
              **総行数:** ${rowCount}行（ヘッダー除く）
              
              ### データ概要
              \`\`\`
              ${csvContent.split('\n').slice(0, 10).join('\n')}
              ${csvContent.split('\n').length > 10 ? '...' : ''}
              \`\`\``;
            } else {
              comment = `## PR Comments Export ⚠️
              
              CSVファイルの生成に失敗しました。
              
              **原因:** コメントデータが見つからないか、エラーが発生しました。
              **生成日時:** ${new Date().toISOString()}
              
              ### 考えられる原因
              - リポジトリにPRが存在しない
              - PRにコメントが存在しない
              - GitHub APIのレート制限
              - 権限の問題`;
            }
          } catch (error) {
            comment = `## PR Comments Export ❌
            
            CSVファイルの処理中にエラーが発生しました。
            
            **エラー:** ${error.message}
            **生成日時:** ${new Date().toISOString()}`;
          }
          
          try {
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
            console.log('コメントが正常に投稿されました。');
          } catch (commentError) {
            console.log('コメントの投稿に失敗しました。アーティファクトから結果を確認してください。');
            console.log('エラー詳細:', commentError.message);
            console.log('リポジトリ情報:', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              is_fork: context.payload.pull_request.head.repo.full_name !== context.payload.repository.full_name
            });
          }
          
    - name: Comment on fork PR
      if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
      run: |
        echo "フォークされたリポジトリからのPRのため、コメントの投稿をスキップします。"
        echo "CSVファイルはアーティファクトとして保存されています。" 